"""12

Revision ID: 96830c13bbd1
Revises: 219a9a2c09c8
Create Date: 2020-10-30 14:00:39.422280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96830c13bbd1'
down_revision = '219a9a2c09c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversation_last_message_datetime'), 'conversation', ['last_message_datetime'], unique=False)
    op.create_index(op.f('ix_messages_datetime'), 'messages', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_datetime'), table_name='messages')
    op.drop_index(op.f('ix_conversation_last_message_datetime'), table_name='conversation')
    # ### end Alembic commands ###
